import os 

general = dict(
    app_name = "Housing Parser",
    internet_check = True,
    internet_host = "https://www.google.com",
    internet_port = 443,
    internet_retries = 3,
    internet_timeout = 30,
    file_type = "json",
    base_dir = os.path.dirname(os.path.abspath(__file__)),
    file_name = "data.json"
)

site_config = {
    "Deanwood": {
        "url": "https://deanwood.im/search/location/188/department/residential-sales/maximum_price/800000/minimum_bedrooms/3/exclude/1/",
        "page_class": ".page-numbers li a.page-numbers",
        "list_box": "grid-box",
        "address": "property-archive-title",
        "address_element": "h4",
        "price": "property-archive-price",
        "price_element": "",
        "image_url": "grid-img",
        "image_element": "img",
        "image_attrs": "src",
        "house_url": "",
        "house_element": "a",
        "house_attrs": "href",
    },
        "GarforthGray": {
        "url": "https://www.garforthgray.im/assets/inc/ajax.php?submitform=1&order=latest&page=1&secondary_school_1=&primary_school_1=&postcode1=&keyword=&ajaxGetSaleResults=1&modal_search=&sale_min_price=&sale_max_price=800000&type_loc%5B%5D=East&type_bed=&type_bath=3",
        "page_class": ".page-item:not(.active):not(.next) .page-link",
        "list_box": "properties-list-item",
        "address": "text-card-link",
        "address_element": "p",
        "price": "price",
        "price_element": "",
        "image_url": "gallery-property",
        "image_element": "div",
        "image_attrs": "data-bg",
        "house_url": "",
        "house_element": "a",
        "house_attrs": "href",
    },
    "Partners": {
        "url": "https://www.partners.co.im/property-for-sale/property/3-bed/all-location?pmax=800000&exclude=1",
        "page_class": ".pagination li:not(.active):not(.prev):not(.next) a",
        "list_box": "card--list",
        "address": "card__title",
        "address_element": "",
        "price": "price-value",
        "price_element": "",
        "image_url": "card__image",
        "image_element": "img",
        "image_attrs": "src",
        "house_element": "a",
        "house_attrs": "href",
    },
    "BlackGraceCowley": {
        "url": "https://www.blackgracecowley.com/search/?PropertySearch%5BsearchType%5D=&PropertySearch%5BsearchType%5D=1&PropertySearch%5BminPrice%5D=0&PropertySearch%5BmaxPrice%5D=800000&PropertySearch%5Bterm%5D=&PropertySearch%5BsortOrder%5D=&PropertySearch%5Bbedroom%5D=3&PropertySearch%5Breception%5D=&PropertySearch%5BpropertyType%5D=&PropertySearch%5Barea%5D=6",
        "page_class": ".pagination a.page",
        "list_box": "property",
        "address": "",
        "address_element": "h3",
        "price": "color-primary",
        "price_element": "",
        "price_regex": r"[\d,.]+",
        "image_url": "property__feature-image",
        "image_element": "img",
        "image_attrs": "src",
        "house_element": "a",
        "house_attrs": "href",
    },
    "Chrystals": {
        "url": "https://www.chrystals.co.im/properties?eapowquicksearch=1&limitstart=0",
        "method": "POST",
        "ajax_endpoint": "https://www.chrystals.co.im/properties?eapowquicksearch=1&limitstart=0",
        "token_type": "joomla",
        "post_params": {
            "filter_cat": "1",
            "filter_beds": "3",
            "filter_price_high": "800000",
            "filter_price_low": "0",
            "eapow-qsmod-location[]": ["184475","170112","184476","279648","170113","170114","170115","170116","170117","170118","170119","170120","170121","170122","170123"],
        },
        "pagination_type": "post_then_follow",
        "page_class": "a.pagenav",
        "list_box": "eapow-overview-row",
        "address": "eapow-overview-title",
        "address_element": "h3",
        "price": "eapow-overview-price",
        "price_element": "",
        "price_regex": r"[\d,.]+",
        "image_url": "eapow-property-thumb-holder",
        "image_element": "img",
        "image_attrs": "data-src",
        "house_element": "a",
        "house_attrs": "href",
    },
    "ManxMove": {
        "url": "https://www.manxmove.im/search-list/?instruction_type=sale&orderby=&address_keyword=&tpj-area=east&maxprice=750000&min_bedrooms=3&showstc=on&property_type=",
        "page_class": ".page-item.inactive .page-link",
        "list_box": "list-property-card",
        "address": "property__address",
        "address_element": "",
        "price": "property__price",
        "price_element": "",
        "price_regex": r"[\d,.]+",
        "image_url": "list__grid-image-container",
        "image_element": "img",
        "image_attrs": "data-src",
        "house_element": "a",
        "house_attrs": "href",
    },
    "Grays": {
        "url": "https://graysestateagents.com/listings?saleOrRental=Sale&maxprice=750000&rental_period=week&status=all&viewType=gallery&sortby=dateListed-desc",
        "pagination_type": "follow_next",
        "page_class": "a.v2-pagination-active",
        "list_box": "v2-gap-y-3",
        "address": "",
        "address_element": "h4",
        "price": "v2-text-primary-500",
        "price_element": "",
        "image_url": "",
        "image_element": "img",
        "image_attrs": "src",
        "image_select": "img[data-testid='shared-image-component']",
        "house_element": "a",
        "house_attrs": "href",
    }
}
